server:
 port: 8071
spring:
  application:
    name: "configserver"
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
        # native:
          # search-locations: "classpath:/config"
          # search-locations: "file:///Users//eazybytes//Documents//config"
        git:
          #uri: "https://github.com/eazybytes/eazybytes-config.git"
          uri: "https://github.com/Nikhil0301/eazybytes.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
          
encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"